# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(
    ['main.py'],
    pathex=['C:\\Users\\user\\Desktop\\SE20\\unogame'],
    binaries=[],
    datas=[('./resources/fonts/Pixeltype.ttf', './resources/fonts'),
('./resources/music/*.mp3', './resources/music'),
('./resources/sounds/*.mp3', './resources/sounds'),
('./resources/images/*.png', './resources/images'),
('./resources/images/card/normalMode/*.png', './resources/images/card/normalMode'),
('./resources/images/card/normalMode/0/*.png', './resources/images/card/normalMode/0'),
('./resources/images/card/normalMode/1/*.png', './resources/images/card/normalMode/1'),
('./resources/images/card/normalMode/2/*.png', './resources/images/card/normalMode/2'),
('./resources/images/card/normalMode/3/*.png', './resources/images/card/normalMode/3'),
('./resources/images/card/normalMode/4/*.png', './resources/images/card/normalMode/4'),
('./resources/images/card/normalMode/5/*.png', './resources/images/card/normalMode/5'),
('./resources/images/card/normalMode/6/*.png', './resources/images/card/normalMode/6'),
('./resources/images/card/normalMode/7/*.png', './resources/images/card/normalMode/7'),
('./resources/images/card/normalMode/8/*.png', './resources/images/card/normalMode/8'),
('./resources/images/card/normalMode/9/*.png', './resources/images/card/normalMode/9'),
('./resources/images/card/normalMode/block/*.png', './resources/images/card/normalMode/block'),
('./resources/images/card/normalMode/change/*.png', './resources/images/card/normalMode/change'),
('./resources/images/card/normalMode/plus2/*.png', './resources/images/card/normalMode/plus2'),
('./resources/images/card/normalMode/plus4/*.png', './resources/images/card/normalMode/plus4'),
('./resources/images/card/normalMode/reverse/*.png', './resources/images/card/normalMode/reverse'),
('./resources/images/card/RG/0/*.png', './resources/images/card/RG/0'),
('./resources/images/card/RG/1/*.png', './resources/images/card/RG/1'),
('./resources/images/card/RG/2/*.png', './resources/images/card/RG/2'),
('./resources/images/card/RG/3/*.png', './resources/images/card/RG/3'),
('./resources/images/card/RG/4/*.png', './resources/images/card/RG/4'),
('./resources/images/card/RG/5/*.png', './resources/images/card/RG/5'),
('./resources/images/card/RG/6/*.png', './resources/images/card/RG/6'),
('./resources/images/card/RG/7/*.png', './resources/images/card/RG/7'),
('./resources/images/card/RG/8/*.png', './resources/images/card/RG/8'),
('./resources/images/card/RG/9/*.png', './resources/images/card/RG/9'),
('./resources/images/card/RG/block/*.png', './resources/images/card/RG/block'),
('./resources/images/card/RG/change/*.png', './resources/images/card/RG/change'),
('./resources/images/card/RG/plus2/*.png', './resources/images/card/RG/plus2'),
('./resources/images/card/RG/plus4/*.png', './resources/images/card/RG/plus4'),
('./resources/images/card/RG/reverse/*.png', './resources/images/card/RG/reverse'),
('./resources/images/card/YB/0/*.png', './resources/images/card/YB/0'),
('./resources/images/card/YB/1/*.png', './resources/images/card/YB/1'),
('./resources/images/card/YB/2/*.png', './resources/images/card/YB/2'),
('./resources/images/card/YB/3/*.png', './resources/images/card/YB/3'),
('./resources/images/card/YB/4/*.png', './resources/images/card/YB/4'),
('./resources/images/card/YB/5/*.png', './resources/images/card/YB/5'),
('./resources/images/card/YB/6/*.png', './resources/images/card/YB/6'),
('./resources/images/card/YB/7/*.png', './resources/images/card/YB/7'),
('./resources/images/card/YB/8/*.png', './resources/images/card/YB/8'),
('./resources/images/card/YB/9/*.png', './resources/images/card/YB/9'),
('./resources/images/card/YB/block/*.png', './resources/images/card/YB/block'),
('./resources/images/card/YB/change/*.png', './resources/images/card/YB/change'),
('./resources/images/card/YB/plus2/*.png', './resources/images/card/YB/plus2'),
('./resources/images/card/YB/plus4/*.png', './resources/images/card/YB/plus4'),
('./resources/images/card/YB/reverse/*.png', './resources/images/card/YB/reverse'),
('./resources/images/achievement/*.png', './resources/images/achievement'),
('./resources/images/menu/*.png', './resources/images/menu'),
('./resources/images/play/*.png', './resources/images/play'),
('./resources/images/storymode/*.png', './resources/images/storymode')],
    hiddenimports=[
    'os',
    'network.__init__',
    'network.client',
    'network.server',
    'utils.__init__',
    'utils.achievement',
    'utils.achieveMenu',
    'utils.menu',
    'utils.multiMenu',
    'utils.storyMode',
    'utils.settings',
    'utils.sound',
    'utils.stageA',
    'utils.stageB',
    'utils.stageC',
    'utils.stageD',
    'single_play',
    'multi_play',
    'pause',
    'models.__init__',
    'models.AI_A',
    'models.AI_B',
    'models.AI_C',
    'models.AI_D',
    'models.AI',
    'models.animation',
    'models.button',
    'models.card',
    'models.deck',
    'models.event',
    'models.Human',
    'models.player'
],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='main',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)